# Generated by Django 5.2 on 2025-04-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion1', models.CharField(max_length=50)),
                ('champion1_role', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('middle', 'Middle'), ('bottom', 'Bottom'), ('support', 'Support')], max_length=10)),
                ('champion2', models.CharField(max_length=50)),
                ('champion2_role', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('middle', 'Middle'), ('bottom', 'Bottom'), ('support', 'Support')], max_length=10)),
                ('interaction_type', models.CharField(choices=[('synergy', 'Synergy'), ('matchup', 'Matchup')], max_length=10)),
                ('win_rate', models.FloatField()),
                ('delta_wr', models.FloatField()),
                ('sample_size', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['champion1', 'champion1_role', 'interaction_type'], name='recomm_cham_champio_180f28_idx'), models.Index(fields=['champion2', 'champion2_role'], name='recomm_cham_champio_7b78d1_idx')],
            },
        ),
    ]
