# Generated by Django 5.2 on 2025-04-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='recomm_cham_name_22b689_idx')],
            },
        ),
    ]
